// PSBT (BIP-174) inspection and re-serialization for EntropyLab, backed by
// rust-bitcoin 0.32.102 compiled to WebAssembly (Rust crate in psbt-wasm/,
// artifact generated by scripts/build-wasm.mjs into psbt-wasm-b64.js).
//
// Two functions cross the boundary, both over the same two-call convention
// (null output pointer reports the required capacity):
//
//   psbtInspectDoc(bytes) -> structured document describing the unsigned
//     transaction, every key-value pair of every map (typed decode for known
//     BIP-174/BIP-371 keys, raw hex for unknown ones), totals and fee, and
//     rust-bitcoin's own parse verdict.
//   psbtBuildBytes(doc)   -> PSBT bytes, after rust-bitcoin's
//     Psbt::deserialize has accepted the rebuilt file.
//
// Nothing here holds keys or generates randomness; the module only ever sees
// PSBT bytes and UTF-8 JSON. But a pasted PSBT can carry an xprv in a
// proprietary field, and rust-bitcoin's parse frames spill into the WASM
// shadow stack, which lives in linear memory and is not erased when a frame
// pops. psbt_free zeroes the heap buffers; the stack region is zeroed once
// per task after any export ran, exactly as in entropylab-wasm.js
// (wasm-stack-scrub.js). Loading mirrors entropylab-wasm.js: browsers compile
// asynchronously (app boot waits for psbtWasmReady to settle, then runs the
// PSBT self-test vectors if it loaded; see self-test.js), Node initializes
// synchronously at import time so the test suite stays synchronous.
import { PSBT_WASM_B64 } from "./psbt-wasm-b64.js";
import { makeStackScrub, overwriteWithPatterns } from "./wasm-stack-scrub.js";

const wasmBytes = (() => {
  const binary = atob(PSBT_WASM_B64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();

const stack = makeStackScrub(wasmBytes);
// Test-facing mirrors of the crypto module's scrubSurface assertions.
export const psbtWasmStackTop = () => stack.stackTop;

let wasm = null; // Wrapped WebAssembly exports; set by init below.

const bind = (instance) => {
  stack.bind(instance);
  wasm = stack.guard(instance.exports);
};

const isNode = typeof process !== "undefined" && !!(process.versions && process.versions.node);
if (isNode) {
  // Node has no synchronous-compilation size limit; tests stay synchronous.
  bind(new WebAssembly.Instance(new WebAssembly.Module(wasmBytes), {}));
}
export const psbtWasmReady = isNode
  ? Promise.resolve()
  : WebAssembly.instantiate(wasmBytes, {}).then(({ instance }) => bind(instance));

let retired = false;
const requireReady = () => {
  if (retired) throw new Error("This session has ended; reload the page to start a new one.");
  if (!wasm) throw new Error("PSBT WebAssembly is not initialized yet; await psbtWasmReady.");
};
// End session: overwrites the whole linear memory with patterns, ending at
// zero, and drops the instance, as retireWasm does for the crypto module;
// every later call is refused.
export const retirePsbtWasm = ({ onPass } = {}) => {
  if (wasm) overwriteWithPatterns(new Uint8Array(wasm.memory.buffer), onPass);
  wasm = null;
  retired = true;
};
// The WASM heap can grow during a call, detaching earlier views; take a fresh
// view of the whole buffer whenever memory is touched.
const heap = () => new Uint8Array(wasm.memory.buffer);
// The scrub tests observe the loader's own instance, not a second module.
export const psbtLoaderHeap = () => {
  requireReady();
  return heap();
};

const encoder = new TextEncoder();
const decoder = new TextDecoder();

const lastError = () => {
  const needed = wasm.psbt_last_error(0, 0);
  if (needed <= 0) return "unknown PSBT WASM error";
  const ptr = wasm.psbt_alloc(needed);
  try {
    const length = wasm.psbt_last_error(ptr, needed);
    return length > 0 ? decoder.decode(heap().slice(ptr, ptr + length)) : "unknown PSBT WASM error";
  } finally {
    wasm.psbt_free(ptr, needed);
  }
};

// Copies `input` into WASM memory, runs export `name` as
// `(inPtr, inLen, outPtr, outCap)` with the two-call capacity convention,
// and returns the produced bytes.
const call = (input, name) => {
  requireReady();
  const fn = wasm[name];
  const inPtr = wasm.psbt_alloc(input.length);
  heap().set(input, inPtr);
  try {
    const needed = fn(inPtr, input.length, 0, 0);
    if (needed < 0) throw new Error(lastError());
    const outPtr = wasm.psbt_alloc(needed);
    try {
      const length = fn(inPtr, input.length, outPtr, needed);
      if (length < 0) throw new Error(lastError());
      return heap().slice(outPtr, outPtr + length);
    } finally {
      wasm.psbt_free(outPtr, needed);
    }
  } finally {
    wasm.psbt_free(inPtr, input.length);
  }
};

// Parses a PSBT (raw bytes) into the editor document. Throws on malformed
// input; the error message comes from the Rust side.
export const psbtInspectDoc = (bytes) => {
  if (!(bytes instanceof Uint8Array) || !bytes.length) throw new Error("PSBT must be a non-empty byte array.");
  return JSON.parse(decoder.decode(call(bytes, "psbt_inspect")));
};

// Rebuilds PSBT bytes from a (possibly edited) editor document. Throws when
// the result would not parse as a PSBT under rust-bitcoin — and, unless
// `insane` is set, when the document fails the consensus layer (transaction
// sanity, UTXO claims, final scripts) listed in the inspect document's
// `problems`. Insane mode skips that layer only: structural PSBT validity is
// still enforced, so the output is always a parseable PSBT.
export const psbtBuildBytes = (doc, { insane = false } = {}) => {
  if (!doc || typeof doc !== "object") throw new Error("editor document must be an object.");
  return call(encoder.encode(JSON.stringify(insane ? { ...doc, insane: true } : doc)), "psbt_build");
};
